import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialSchema1700000000000 implements MigrationInterface {
  async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 0');
    await queryRunner.query("CREATE TABLE `achievement` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `slug` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `description` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `category` enum('sentinel','specialist','investigator','consistency','elite') COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `rarity` enum('common','uncommon','rare','epic','legendary') COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `requirement_type` enum('total_xp','level','challenges_completed','lessons_completed','streak','arcade_plays','perfect_arcade_runs') COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `requirement_value` int NOT NULL,\r\n  `tier` int NOT NULL DEFAULT '1',\r\n  `icon` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `reward_prestige` int NOT NULL DEFAULT '1',\r\n  `prerequisite_slug` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `position_x` int NOT NULL DEFAULT '0',\r\n  `position_y` int NOT NULL DEFAULT '0',\r\n  `order_index` int NOT NULL DEFAULT '0',\r\n  `secret` tinyint NOT NULL DEFAULT '0',\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\r\n  `image_url` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `IDX_94c26456494d9a848fa8f4ef1e` (`slug`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `achievement_connection` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `from_slug` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `to_slug` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `kind` enum('primary','cross') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'primary',\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `UQ_achievement_connection_edge` (`from_slug`,`to_slug`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `arcade_game` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `slug` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `game_type` enum('quiz','phishing','data_classify','client_only') COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `title` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `description` varchar(300) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `tag` varchar(40) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `xp_base` int NOT NULL,\r\n  `color` varchar(9) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `color_dark` varchar(9) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `image` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `IDX_b2bf6a39ef408d894aeaf54aae` (`slug`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `aula` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `modulo_id` int NOT NULL,\r\n  `title` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `description` varchar(1000) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `type` enum('video','quadrinho') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'video',\r\n  `content_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `pages` json DEFAULT NULL,\r\n  `duration` int NOT NULL DEFAULT '0',\r\n  `xp` int NOT NULL DEFAULT '0',\r\n  `order` int NOT NULL DEFAULT '0',\r\n  `section_name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `uq_aula_modulo_order` (`modulo_id`,`order`),\r\n  CONSTRAINT `FK_3db97a2663ca20a18882b923062` FOREIGN KEY (`modulo_id`) REFERENCES `modulo` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `aula_quiz` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `aula_id` int NOT NULL,\r\n  `text` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `options` json NOT NULL,\r\n  `correct_index` int NOT NULL,\r\n  `order` int NOT NULL DEFAULT '0',\r\n  PRIMARY KEY (`id`),\r\n  KEY `FK_dece15e05a4ba72ab088b96b738` (`aula_id`),\r\n  CONSTRAINT `FK_dece15e05a4ba72ab088b96b738` FOREIGN KEY (`aula_id`) REFERENCES `aula` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `benefits` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `description` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `icon` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `color` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `textColor` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `borderColor` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `glow` tinyint NOT NULL DEFAULT '1',\r\n  PRIMARY KEY (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `challenge` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `title` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `description` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `difficulty` enum('iniciante','intermediario','avancado') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'iniciante',\r\n  `duration` int NOT NULL,\r\n  `points` int NOT NULL,\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  `image` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  PRIMARY KEY (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `convite` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `token_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `email` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `empresa_id` int NOT NULL,\r\n  `criado_por_id` int NOT NULL,\r\n  `expires_at` datetime NOT NULL,\r\n  `max_uses` int NOT NULL DEFAULT '1',\r\n  `uses` int NOT NULL DEFAULT '0',\r\n  `revoked` tinyint NOT NULL DEFAULT '0',\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\r\n  `role` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'user',\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `IDX_dabf013b5df084454647921b46` (`token_hash`),\r\n  KEY `FK_521c3b5372f3cf6c185648a60e4` (`empresa_id`),\r\n  KEY `FK_1edd00acd4eb65b7bf3717ee71c` (`criado_por_id`),\r\n  CONSTRAINT `FK_1edd00acd4eb65b7bf3717ee71c` FOREIGN KEY (`criado_por_id`) REFERENCES `usuario` (`id`),\r\n  CONSTRAINT `FK_521c3b5372f3cf6c185648a60e4` FOREIGN KEY (`empresa_id`) REFERENCES `empresa` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `cosmetic_item` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `slug` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `description` varchar(400) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `type` enum('frame','background','title','badge','effect') COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `rarity` enum('common','uncommon','rare','epic','legendary') COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `price` int NOT NULL,\r\n  `visual_value` varchar(160) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `required_achievement_slug` varchar(80) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `IDX_0537be4051d3522f56e35064a3` (`slug`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `data_item` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `label` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `correct_level` enum('publico','interno','confidencial','secreto') COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `explanation` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  PRIMARY KEY (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `empresa` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `nome` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `logo_url` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `paleta` json DEFAULT NULL,\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\r\n  `parametros_funcionalidades` json DEFAULT NULL,\r\n  `system_key` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `ux_empresa_system_key` (`system_key`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `empresa_parametros_audit` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `empresa_id` int NOT NULL,\r\n  `alterado_por_id` int NOT NULL,\r\n  `anterior` json NOT NULL,\r\n  `atual` json NOT NULL,\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`),\r\n  KEY `ix_empresa_parametros_empresa_data` (`empresa_id`,`created_at`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `modulo` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `title` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `description` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `thumbnail` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `type` enum('video','quadrinho','misto') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'misto',\r\n  `category` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `difficulty` enum('iniciante','intermediario','avancado') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'iniciante',\r\n  `xp_total` int NOT NULL DEFAULT '0',\r\n  `xp_bonus` int NOT NULL DEFAULT '0',\r\n  `order` int NOT NULL DEFAULT '0',\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `notification` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `message` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `readed` tinyint NOT NULL DEFAULT '0',\r\n  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,\r\n  PRIMARY KEY (`id`),\r\n  KEY `ix_notification_usuario_read_created` (`usuario_id`,`readed`,`created_at`),\r\n  KEY `ix_notification_usuario_created` (`usuario_id`,`created_at`),\r\n  CONSTRAINT `FK_b09042f74f25b226c35a9ac3cd2` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `pending_registration` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `token_hash` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `birth_date` date NOT NULL,\r\n  `nickname` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `kind` varchar(16) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `invite_id` int DEFAULT NULL,\r\n  `expires_at` datetime NOT NULL,\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  `last_sent_at` datetime DEFAULT NULL,\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `ux_pending_registration_token` (`token_hash`),\r\n  UNIQUE KEY `ux_pending_registration_email` (`email`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `phishing_sample` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `kind` enum('email','site','message') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'email',\r\n  `content` json NOT NULL,\r\n  `is_phishing` tinyint NOT NULL,\r\n  `signals` json NOT NULL,\r\n  `explanation` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `difficulty` enum('iniciante','intermediario','avancado') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'iniciante',\r\n  `active` tinyint NOT NULL DEFAULT '1',\r\n  PRIMARY KEY (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `prestige_transaction` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `amount` int NOT NULL,\r\n  `type` enum('level','achievement','purchase','adjustment') COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `source_key` varchar(140) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `description` varchar(240) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `UQ_prestige_transaction_usuario_source` (`usuario_id`,`source_key`),\r\n  CONSTRAINT `FK_e8ec7213e1c93c24e473598c889` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `prestige_wallet` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `balance` int NOT NULL DEFAULT '0',\r\n  `total_earned` int NOT NULL DEFAULT '0',\r\n  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `UQ_prestige_wallet_usuario` (`usuario_id`),\r\n  UNIQUE KEY `REL_858fc7181fcad63efdb8c0a4ef` (`usuario_id`),\r\n  CONSTRAINT `FK_858fc7181fcad63efdb8c0a4efe` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `question` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `challenge_id` int NOT NULL,\r\n  `text` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `options` json NOT NULL,\r\n  `correct_index` int NOT NULL,\r\n  `explanation` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `order` int NOT NULL DEFAULT '0',\r\n  PRIMARY KEY (`id`),\r\n  KEY `ix_question_challenge_order` (`challenge_id`,`order`),\r\n  CONSTRAINT `FK_766396453e320ea54af1e5ab351` FOREIGN KEY (`challenge_id`) REFERENCES `challenge` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `usuario` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `level` int NOT NULL DEFAULT '1',\r\n  `role` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'user',\r\n  `empresa_id` int DEFAULT NULL,\r\n  `nickname` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `nickname_pending` varchar(24) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `nickname_request_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'none',\r\n  `profile_image_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,\r\n  `birth_date` date DEFAULT NULL,\r\n  `email_verified_at` datetime DEFAULT NULL,\r\n  `trial_started_at` datetime DEFAULT NULL,\r\n  `trial_ends_at` datetime DEFAULT NULL,\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `ux_usuario_email` (`email`),\r\n  KEY `FK_f3ec4943ff70f8567cf5e63182c` (`empresa_id`),\r\n  CONSTRAINT `FK_f3ec4943ff70f8567cf5e63182c` FOREIGN KEY (`empresa_id`) REFERENCES `empresa` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `usuario_achievement` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `achievement_id` int NOT NULL,\r\n  `progress` int NOT NULL DEFAULT '0',\r\n  `unlocked` tinyint NOT NULL DEFAULT '0',\r\n  `unlocked_at` datetime DEFAULT NULL,\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `UQ_usuario_achievement_usuario_achievement` (`usuario_id`,`achievement_id`),\r\n  KEY `FK_5d4c5fd381ce09ccd201027bf54` (`achievement_id`),\r\n  CONSTRAINT `FK_5d4c5fd381ce09ccd201027bf54` FOREIGN KEY (`achievement_id`) REFERENCES `achievement` (`id`),\r\n  CONSTRAINT `FK_8dba3544808965df653ea986f8e` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `usuario_arcade_stats` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `game_slug` varchar(80) COLLATE utf8mb4_unicode_ci NOT NULL,\r\n  `total_plays` int NOT NULL DEFAULT '0',\r\n  `perfect_runs` int NOT NULL DEFAULT '0',\r\n  `best_score` int NOT NULL DEFAULT '0',\r\n  `last_played_at` datetime DEFAULT NULL,\r\n  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `UQ_usuario_arcade_stats_usuario_game` (`usuario_id`,`game_slug`),\r\n  CONSTRAINT `FK_4390e828502a52fc58b740aeebb` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `usuario_aula` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `aula_id` int NOT NULL,\r\n  `completed` tinyint NOT NULL DEFAULT '0',\r\n  `completed_at` datetime DEFAULT NULL,\r\n  `started_at` datetime DEFAULT NULL,\r\n  `last_accessed_at` datetime DEFAULT NULL,\r\n  `progress_percent` int NOT NULL DEFAULT '0',\r\n  `last_video_second` int DEFAULT NULL,\r\n  `last_page` int DEFAULT NULL,\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `UQ_usuario_aula_usuario_aula` (`usuario_id`,`aula_id`),\r\n  KEY `FK_67cf57d2177123fe59ccd2b352b` (`aula_id`),\r\n  KEY `ix_usuario_aula_usuario_completed` (`usuario_id`,`completed`),\r\n  CONSTRAINT `FK_16eeb89082741dd5844b1f33473` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`),\r\n  CONSTRAINT `FK_67cf57d2177123fe59ccd2b352b` FOREIGN KEY (`aula_id`) REFERENCES `aula` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `usuario_challenge` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `challenge_id` int NOT NULL,\r\n  `progress` int NOT NULL DEFAULT '0',\r\n  `completed` tinyint NOT NULL DEFAULT '0',\r\n  `started_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  `completed_at` datetime DEFAULT NULL,\r\n  `answered_question_ids` json DEFAULT NULL,\r\n  PRIMARY KEY (`id`),\r\n  KEY `FK_ec7fc306c4c5fa20b4fd184d6d8` (`challenge_id`),\r\n  KEY `ix_usuario_challenge_usuario_challenge` (`usuario_id`,`challenge_id`),\r\n  KEY `ix_usuario_challenge_usuario_completed` (`usuario_id`,`completed`),\r\n  CONSTRAINT `FK_1cb2c5889a26274e6f3d670b8b4` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`),\r\n  CONSTRAINT `FK_ec7fc306c4c5fa20b4fd184d6d8` FOREIGN KEY (`challenge_id`) REFERENCES `challenge` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `usuario_cosmetic` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `cosmetic_item_id` int NOT NULL,\r\n  `equipped` tinyint NOT NULL DEFAULT '0',\r\n  `purchased_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `UQ_usuario_cosmetic_usuario_item` (`usuario_id`,`cosmetic_item_id`),\r\n  KEY `FK_10a090bb7f45dc4cbb0a42fc503` (`cosmetic_item_id`),\r\n  CONSTRAINT `FK_10a090bb7f45dc4cbb0a42fc503` FOREIGN KEY (`cosmetic_item_id`) REFERENCES `cosmetic_item` (`id`),\r\n  CONSTRAINT `FK_defd396cba3236f757c192a9c49` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query("CREATE TABLE `usuario_stats` (\r\n  `id` int NOT NULL AUTO_INCREMENT,\r\n  `usuario_id` int NOT NULL,\r\n  `total_points` int NOT NULL DEFAULT '0',\r\n  `current_streak` int NOT NULL DEFAULT '0',\r\n  `last_checkin_date` date DEFAULT NULL,\r\n  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),\r\n  PRIMARY KEY (`id`),\r\n  UNIQUE KEY `IDX_d3887be59a0ffd813fe8a2880d` (`usuario_id`),\r\n  UNIQUE KEY `REL_d3887be59a0ffd813fe8a2880d` (`usuario_id`),\r\n  CONSTRAINT `FK_d3887be59a0ffd813fe8a2880d6` FOREIGN KEY (`usuario_id`) REFERENCES `usuario` (`id`)\r\n) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;");
    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 1');
  }
  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 0');
    await queryRunner.query('DROP TABLE IF EXISTS `usuario_stats`');
    await queryRunner.query('DROP TABLE IF EXISTS `usuario_cosmetic`');
    await queryRunner.query('DROP TABLE IF EXISTS `usuario_challenge`');
    await queryRunner.query('DROP TABLE IF EXISTS `usuario_aula`');
    await queryRunner.query('DROP TABLE IF EXISTS `usuario_arcade_stats`');
    await queryRunner.query('DROP TABLE IF EXISTS `usuario_achievement`');
    await queryRunner.query('DROP TABLE IF EXISTS `usuario`');
    await queryRunner.query('DROP TABLE IF EXISTS `question`');
    await queryRunner.query('DROP TABLE IF EXISTS `prestige_wallet`');
    await queryRunner.query('DROP TABLE IF EXISTS `prestige_transaction`');
    await queryRunner.query('DROP TABLE IF EXISTS `phishing_sample`');
    await queryRunner.query('DROP TABLE IF EXISTS `pending_registration`');
    await queryRunner.query('DROP TABLE IF EXISTS `notification`');
    await queryRunner.query('DROP TABLE IF EXISTS `modulo`');
    await queryRunner.query('DROP TABLE IF EXISTS `empresa_parametros_audit`');
    await queryRunner.query('DROP TABLE IF EXISTS `empresa`');
    await queryRunner.query('DROP TABLE IF EXISTS `data_item`');
    await queryRunner.query('DROP TABLE IF EXISTS `cosmetic_item`');
    await queryRunner.query('DROP TABLE IF EXISTS `convite`');
    await queryRunner.query('DROP TABLE IF EXISTS `challenge`');
    await queryRunner.query('DROP TABLE IF EXISTS `benefits`');
    await queryRunner.query('DROP TABLE IF EXISTS `aula_quiz`');
    await queryRunner.query('DROP TABLE IF EXISTS `aula`');
    await queryRunner.query('DROP TABLE IF EXISTS `arcade_game`');
    await queryRunner.query('DROP TABLE IF EXISTS `achievement_connection`');
    await queryRunner.query('DROP TABLE IF EXISTS `achievement`');
    await queryRunner.query('SET FOREIGN_KEY_CHECKS = 1');
  }
}

